### ISSUE TITLE
TODO 리스트

### ISSUE THREAD

**Issue by chshin59** [chshin59/discord-study-bot#2]
### 개발
- [ ] 타입스크립트 전환
- [ ] config.json vs dotenv
- [ ] User

### 배포
- [ ] cloudflare 첫 배포 해보기
- [ ] github action 추가
(main merge시 배포)

**Comment by chshin59** [comment]
@smj53 @baalftgg @khlee025 언제든 추가해주세요~
